{% set name = "dnslib" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbd20a7cd704836923be8e130f0da6c3d840f14ac04590fae420a41d1f1be6fb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - dnslib

about:
  home: http://bitbucket.org/paulc/dnslib/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple library to encode/decode DNS wire-format packets
  doc_url: https://pypi.org/project/dnslib/
  dev_url: https://bitbucket.org/paulc/dnslib/src/default/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
